name: Forum API Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: testuser
      PGPASSWORD: testpass
      PGDATABASE: testdb
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done
        
      - name: Create test.json config
        run: |
          mkdir -p config/database
          cat <<EOF > config/database/test.json
          {
            "dev": {
              "driver": "pg",
              "user": "testuser",
              "password": "testpass",
              "host": "localhost",
              "port": 5432,
              "database": "testdb"
            }
          }
          EOF

      - name: Run migration/seeding if needed
        run: npm run migrate:test

      - name: Run unit & integration tests
        run: npm test